# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

imports:
    - { resource: 'listeners.yml' }

services:
    app.twig_extension:
        class: VelBundle\Twig\VelExtension
        public: false
        arguments:
            - '@session'
            - '@jms_serializer'
        tags:
            - { name: twig.extension }

    app.cart_handler:
        class: VelBundle\Handler\CartHandler
        arguments:
            - '@session'
            - '@logger'
#    service_name:
#        class: VelBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
